def plot_twist(car):
    print(f"Oh no I forgot it's a BMW!")
    car.overheat()
    car.print_temp()
    input()
    print("Stop the engine!!")
    car.stop()
    car.print_temp()
    input()
    print("Just about avoided yet another catastrophe!")
    input()
    print("...")
    input()
    print("...wait, what that puddle under it...?")
